DROP TABLE IF EXISTS Location;

DROP TABLE IF EXISTS Type;

DROP TABLE IF EXISTS Badge;

DROP TABLE IF EXISTS Ability;

DROP TABLE IF EXISTS Species;

DROP TABLE IF EXISTS Egg_Group;

DROP TABLE IF EXISTS Move;

DROP TABLE IF EXISTS Pokemon_2;

DROP TABLE IF EXISTS Pokemon_3;

DROP TABLE IF EXISTS Item_2;

DROP TABLE IF EXISTS Gym_Leader_2;

DROP TABLE IF EXISTS Trainer;

DROP TABLE IF EXISTS Item_1;

DROP TABLE IF EXISTS Pokemon_1;

DROP TABLE IF EXISTS Gym_Leader_1;

DROP TABLE IF EXISTS Player;

DROP TABLE IF EXISTS Species_Evolves_Into;

DROP TABLE IF EXISTS Pokemon_Has_Learned_Move;

DROP TABLE IF EXISTS Species_Has_Type;

DROP TABLE IF EXISTS Species_Can_Learn_Move;

DROP TABLE IF EXISTS Species_Can_Have_Ability;

DROP TABLE IF EXISTS Species_Located_In;

DROP TABLE IF EXISTS Species_Belongs_To_Egg_Group;

DROP TABLE IF EXISTS Player_Owns_Badge;